var exam=[
    {name:"复合句练习题(2)",class:"en",test:[
        {exam:"1.  --- _______do you read English newspapers?--I read China Daily every day.",is:"c",a:"A. How long",b:"B. How soon ",c:"C. How often",d:"D. How far"},
        {exam:"2. John had a short walk after lunch, _______？",is:"b",a:"A.did he",b:" B.didn't he ",c:"C. had he ",d:"D. hadn't he"},
        {exam:"3.  --- _______do you have an Art Festival in your school?---Once a year.",is:"b",a:"A. How long",b:"B. How often ",c:"C. How far",d:"D. How soon"},
        {exam:"4. If you want to go to see the movie this evening, so _______I.",is:"c",a:"A. do ",b:"B.am",c:"C.will ",d:"D. shouldd"},
        {exam:"5. _______tall the girl is!",is:"a",a:"A. How",b:"B. How a",c:"C. What",d:"D. What a"},
        {exam:"6. _______ call me Mimi! It's my cat's name.",is:"d",a:"A. Not",b:"B. Didn't",c:"C. Doesn't",d:"D. Don't"},
        {exam:"7. They went to the park yesterday, ______?",is:"b",a:"A. don't they",b:"B. didn't they",c:"C. aren't they",d:"D. can't they"},
        {exam:"8.  ---Li Mei usually helps others, _______？---Yes, she is kind-hearted.",is:"c",a:"A. does she ",b:"B. is she",c:"C. doesn't she ",d:"D. isn’t she"},
        {exam:"9. There _______an English party in our school tomorrow evening.",is:"d",a:"A. have",b:"B. will have",c:"C. is going to have",d:"D. will be"},
        {exam:"10.  --- _______a year does your school have sports meetings?---Twice a year.",is:"d",a:"A. How often",b:"B. How soon",c:"C. How long",d:"D. How many times"},
        {exam:"11.  ---I have changed my job.---_______.",is:"b",a:"A. So do I ",b:"B. So have I",c:"C. So I do",d:"D. So I have"},
        {exam:"12. Mike learns a lot about Internet. And _______.",is:"b",a:"A. I don't, either",b:"B. so do I",c:"C. so am I",d:"D.I am, too"},
        {exam:"13. Jim never goes to the movies on Saturday, _______？",is:"d",a:"A. does Jim",b:"B. doesn't Jim",c:"C. doesn't he",d:"D. does he"},
        {exam:"14. You've just finished your listening exam. Please get yourself ready for the next part, _______？",is:"b",a:"A. shall we",b:"B. will you",c:"C. What was",d:"D. How is"},
        {exam:"15.  --- _______the weather like last Monday?---It was sunny.",is:"c",a:"A. How was",b:"B. What's",c:"c",d:"d"},
        {exam:"16. _______great scientist Qian Xuesen is!",is:"d",a:"A. How",b:"B. How a",c:"C. What",d:"D. What a"},
        {exam:"17. --- _______do you visit your grandparents?---Once a month.",is:"d",a:"A. How soon ",b:"B. How long",c:"C. How much",d:"D. How often"},
        {exam:"18.  --- _______ do you speak English so well?---Because I practice it with my partner every day.",is:"a",a:"A. Why ",b:"B. When",c:"C. Who"},
        {exam:"19. ---We'll go to Qing Yuan Mountain tomorrow. Why _______join us?---That's a good idea. ",is:"a",a:"A. not",b:"B. don't",c:"C. can't",d:"D. didn't"},
        {exam:"20. There is little milk in the glass, _______？",is:"a",a:"A. is there",b:"B. isn't there",c:"C. isn't it",d:"D. does it"},
        {exam:"21. The students in Class Two played basketball against Class One yesterday,_____?",is:"b",a:"A. did they",b:"B. didn't they",c:"C. weren't they"},
        {exam:"22. ---What a new computer! Can you tell me_______?---Just the day before yesterday.",is:"c",a:"A. how much you paid for it ",b:"B. how much did you pay for it",c:"C. when you bought it",d:"D. when did you buy it"},
        {exam:"23. ---Tom wants to know if you will have a picnic tomorrow.---Yes. But if it _______, we'll play chess instead.",is:"d",a:"A. will rain",b:"A. will rain",c:"C. is raining",d:"D. rains"},
        {exam:"24. ---Do you know    this dictionary belongs to?---Let me see. Oh, it's_______.",is:"d",a:"A. who does; min",b:"B. who; me",c:"C. whose; mine",d:"D. who; mine"},
        {exam:"25. Franklin told them all _______to be in Britain again.",is:"b",a:"A. he was how happy ",b:"B. how happy he was ",c:"C. how was he happy ",d:"D. he was happy how"},
        {exam:"26.  ---What kind of movies do you like?---I like the movies_______ are about Chinese history.",is:"d",a:"A. who",b:"B. whom",c:"C. whose",d:"D. that"},
        {exam:"27.  ---Do you know _______？---Sorry, I don't have a watch.",is:"c",a:"B. whose watch is this",b:"b",c:"C. what time it is",d:"D. what time is it"},
        {exam:"28. The woman asked the policeman where _______.",is:"a",a:"A. the post office is",b:"B. the post office was",c:"C. is the post office ",d:"D. was the post office"},
        {exam:"29. ---Can you guess_______ the new schoolbag yesterday?.----Sorry, I've no idea.",is:"a",a:"A. how much did he pay for",b:"B. how much he spent",c:"C how much he paid for",d:"D. how much did he spend"},
        {exam:"30. Who is the man_______ is reading a book over there?",is:"a",a:"A. that",b:"B. which",c:"C. whose",d:"D. what"},
        {exam:"31. ---Do you know_______?---Next Sunday.",is:"a",a:" A. what they will do",b:"B. where they will do",c:"C. when they will come here",d:"D. who they will meet"},
        {exam:"32. ---Can you tell me why_______?---Because I want to help the people there.",is:"a",a:"A. do you go to Tibet(西藏)",b:"B. did you go to Tibet",c:"C are you going to Tibet",d:"D. you are going to Tibet"},
        {exam:"33. ---Linda, could you tell me _______?  ---He is an actor.",is:"a",a:"A. what he does",b:"B. what does he do",c:"C where he works",d:"D. where does he work"},
        {exam:"34. ---Could you tell me _______?---Sure. The day after tomorrow.",is:"a",a:"A. when will you leave for the U.S.A.",b:"B. when Mr. Lee will come",c:"C when your father returned"},
        {exam:"35. He asked me_______.",is:"a",a:"A. who did kick the first goal in the World Cup",b:"B. when was the A. PEC meeting held",c:"C when China became a member of the WTO",d:"D. where will the 2008 Olympics be held"},
        {exam:"36. Jane is one of the students in the class _______ have ever been to China.",is:"a",a:"A. who ",b:"B. whose",c:"C. which",d:"D. whom"},
        {exam:"37. Can you tell me _______after this exam？",is:"d",a:"A. what you did",b:"B. what did you do",c:"C. what will you do",d:"D. what "},
        {exam:"38. ---Can you tell me how many colours _______ in a rainbow?---Seven",is:"a",a:"A. there are",b:"B. are ther",c:"C. they are",d:"D. are they"},
        {exam:"39. I can't understand _______Apple's iPad 2.",is:"b",a:"A. why are they so mad about",b:"B. why they are so mad about",c:"C. how are they so mad about ",d:"D. how they are so mad about"},
    ]},
    {name:"复合句练习题(1)",class:"en",test:[
        {id:"1",exam:"1．— The Dragon Boat races are so exciting, but our boat is still behind.— Don’t worry. I am sure _______ our team will win!",is:"c",a:"A. if",b:"B. /",c:"C. whether",d:"D. of"},
        {id:"2",exam:"2．Why not listen to BBC news to improve your listening skills?It’s     difficult for me      follow.",is:"b",a:"A. too; to ",b:"B. so; that",c:"C. such; that",d:"D. so; too"},
        {id:"2",exam:"3.— Yesterday there were      many people in the park      I almost lost my way.— It was the May Day holiday. Lots of people wanted to have fun there.",is:"a",a:"A. quite; that",b:"B. so; that",c:"C. enough; that",d:"D. very; that"},
        {id:"2",exam:"4．This lesson was so boring ____ some students began to sleep in class.",is:"c",a:"A. that",b:"B. and",c:"C. when",d:"D. how"},
        {id:"2",exam:"6．---The doctor told me not to eat too much, but I found it difficult.---The doctor is right. _________ you eat, ______ you will be.",is:"a",a:"A. The less, the healthier",b:"B.  The less; the more healthily",c:"C. The more; the healthier",d:"D. The more; the more healthily"},
        {id:"2",exam:"7. —It seems _____ you like to work with children.—Yes, they are so lovely.",is:"d",a:"A. that",b:"B. what",c:"C.to",d:"D.as"},
        {id:"2",exam:"8． I want to know if the idea _______ she has thought up works out fine.",is:"d",a:"A. who",b:"B. where",c:"C. that",d:"D. how"},
        {id:"2",exam:"9．—You speak _____ fast _____ we can’t follow you.",is:"b",a:"—I will speak slowly.",b:"B. such; that",c:"C. such a; that",d:"D. too; to"},
        {id:"2",exam:"10．Are you sure the news ______ you received from the Internet is true?",is:"d",a:"A. that ",b:"B. where",c:"C. what",d:"D. how"},
        {id:"2",exam:"11．—Could you tell me __________？—Sorry, I don’t know.",is:"c",a:"A. how can I get to the Water Sports Center",b:"B. when will Mr. Black come back",c:"C. why is Tom late for class",d:"D. where Mr. Green has gone"},
        {id:"2",exam:"12．These days the long TV play is     popular     my mother often keep  watching it for two hours without a rest a day .",is:"c",a:"A. so, that",b:"B. too , to",c:"C. very , that",d:"D. such , that"},
        
    ]}
];